### ISSUE TITLE
Program breaks with a lot of messages

### ISSUE THREAD

**Issue by carricktoupe** [Maxhem2/instagram-mass-unsender#2]
While this script runs extremely well for a few dozen messages, I've found a larger amount of messages significantly slow down the process (the lower limit being around 100), meaning the time between unsends goes from a second or two to 10-15. In some extreme cases, I've found it completely breaks, getting stuck on the first unsend of the conversation. I believe this may be due to having to process the large amounts of pop-ups when scanning the text of the other person in the DM, or a less efficient sorting algorithm? 

I'm running the latest version of Chrome on a PC with a Ryzen 3100, 16 gb of 3000 mhz ram, and a 5600xt. Latest version of Win 10 as well. 

I appreciate all the work that's gone into this project, and hope this may help improve it.

**Comment by Maxhem2** [comment]
It does not, Instagram has a ratelimit for how many messages you can delete at a time, thus the timeout will get larger and larger

**Comment by carricktoupe** [comment]
Ah, got it. Thanks for the reply
