### ISSUE TITLE
Suggestions for the developer

### ISSUE THREAD

**Issue by roshan-g20** [Maxhem2/instagram-mass-unsender#4]
1: better don't wait for reaching the topmost message of the chat, instead start unsending messages from below itself and start moving upwards, and wait for 1 second for the upper batch of messages to load after all messages that are visible are unsend and new batch of older messages need to load.
2: Instagram might have somehow in the code distinguished that the messages sent by us will be on the right side of the chatbox, so instead of clicking all messages and then clicking more and finding unsend button on all (right&left) messages, adjust the code to click messages in the container on the right side only and then do the next more>unsend>unsend.
3: some timeouts that I'll suggest is 80ms for the first click on the message content, 100 for more, 100 for unsend, 300 for next unsend then wait till 500ms then start again, the code should stop unsending messages as described by point4
4: the code should unsend 65 messages and then pause unsending process for 5 minutes because of Instagram limit to unsend messages, when the 5 minutes waiting period has started the code should now scroll to top to fetch more older messages in advance as when the wait period will get finished the code can rapidly perform the unsending actions without waiting for messages to load,
5: when the 5 minutes wait period is done the code should automatically come down to the latest available message on right side sent by me and should start unsending from there and continue doing it upwards for next 65 messages then stop for 5 minutes and so on

now in short the code goes like this > (starting from below of the page> clicks latest message sent by me in 80ms > clicks more in 100ms > clicks unsend in 100ms > clicks other unsend button in 300ms > waits 500ms and also verifies the message is unsent or not > starts unsending next message > reaches till top of page and sees that more messages are loading > if all messages are unsent and new messages are loading waits for 1 or 2 second > after messages are loaded repeats unseding until 65th message content from the 1st message unsent > pauses the process for 5 minutes after unseding 65th message > scrolls upwards to prefetch more messages > after 5 minutes scrolls to the latest right side message sent by me and starts unsending it till next 65th message)

**Comment by roshan-g20** [comment]
A better rephrased text using chatgpt

1: Instead of waiting to reach the top of the chat, start by unsending messages from the bottom and move upwards. Wait for one second after all visible messages are unsent and new older messages need to load.
2: Instagram may have coded messages sent by us to appear on the right side of the chatbox. Instead of clicking all messages and searching for the unsend button on both sides, modify the code to click messages on the right side only and then proceed with more > unsend > unsend.
3: Suggested timeouts: 80ms for clicking the message content, 100ms for more, 100ms for unsend, 300ms for the next unsend. Wait 500ms before restarting the process. The code should stop unsending messages as described in point 4.
4: The code should unsend 65 messages and then pause for 5 minutes due to Instagram's limit. During the waiting period, scroll to the top to fetch more older messages in advance. After the wait period, rapidly perform unsending actions without waiting for messages to load.
5: After the 5-minute wait, the code should automatically scroll down to the latest message on the right side sent by me and start unsending from there. Continue upwards for the next 65 messages, then pause for 5 minutes, and repeat the process.

**Comment by roshan-g20** [comment]
Finally a Simplified Tree generated using chatgpt if you've still didn't understood and need better clarification

Start Unsending Messages
     Begin at the Bottom
     Click Right-Side Messages
          Click Message Content (80ms)
          Click "More" (100ms)
          Click "Unsend" (100ms)
          Click Second "Unsend" (300ms)
          Verify Unsent (Wait 500ms)
          Move to Next Message
     Reach Top of Page
          Check for Loading Messages (Wait 1-2 seconds)
     Pause for 5 Minutes (Instagram Limit)
          Scroll Up to Prefetch More Messages
          Return to Latest Right-Side Message
          Continue Unsending (Upwards) until 65th Message
     Repeat the Process

**Comment by Maxhem2** [comment]
Thanks for the suggestions. Most issues should be addressed in the new Updated V2
- "Click Right-Side Messages" would require to handle the float of style which is much work.
- Prefetching is overkill in my opinion.
