### ISSUE TITLE
Can't proceed

### ISSUE THREAD

**Issue by goddessinph** [Maxhem2/instagram-mass-unsender#6]
<img width="553" alt="Screenshot 2023-10-03 at 10 21 04 AM" src="https://github.com/Maxhem2/instagram-mass-unsender/assets/146795057/3cbe404e-01d5-44a2-82bc-8b97a0bc744d">

How do i proceed? Thank you

**Comment by Maxhem2** [comment]
It always looks like that but should have started to unsend your messages, please send a screen recording showing what happens

**Comment by goddessinph** [comment]
Nothing is happening as the javascript didn't work on the console?

**Comment by Maxhem2** [comment]
It does work, I repeatedly demand you provide a screen recording of copying and pasting it into the console, then hitting enter and it's failing to work

**Comment by ahmadw13** [comment]
works on mine, must be a local issue

**Comment by Maxhem2** [comment]
Thanks for your feedback, I will close this issue now since the original issuer does not leave any more feedback I will assume it did end up working and he is just lazy.
